"use client";

import "./globals.css";
import type { Metadata } from "next";
import { useState } from "react";
import { Inter } from "next/font/google";
import ButtonAuth from "@/components/navComponents/ButtonAuth";
import NavBar from "@/components/navComponents/NavBar";
import Logo from "@/components/navComponents/logo";
import NavItem from "@/components/navComponents/NavItem";
import SearchBar from "@/components/navComponents/SearchBar";
import Category from "@/components/navComponents/Category";
import Cart from "@/components/navComponents/Cart";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App By dilli",
    description: "Generated by create next app",
};
interface Props {
    children: React.ReactNode;
}

export default function RootLayout({ children }: Props) {
    const [cartCount, setCartCount] = useState(0);

    return (
        <html lang="en">
            <body className={inter.className + " overflow-x-hidden"}>
                <NavBar>
                    <Logo className="hidden md:flex" />
                    <Category></Category>
                    <SearchBar></SearchBar>
                    <Logo className="flex sm:hidden" />

                    <div className="flex justify-around items-center gap-4">
                        <NavItem>Teach on A+</NavItem>
                        <NavItem>Contact us</NavItem>
                    </div>
                    <Cart cartItemCount={cartCount}></Cart>
                    <div className="hidden md:flex md:gap-2">
                        <ButtonAuth pagePath="/signup">Signup</ButtonAuth>
                        <ButtonAuth pagePath="/login">login</ButtonAuth>
                    </div>
                </NavBar>
                {children}
            </body>
        </html>
    );
}
